version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 3000:3000
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: 'npm run test'
    volumes:
      - /app/node_modules
      - .:/app